import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';

import { routes } from './app.routes';
import { environment } from '../environments/environment.prod';

export const appConfig: ApplicationConfig = {
  providers: [provideZoneChangeDetection({ eventCoalescing: true }), provideRouter(routes), provideHttpClient()]
};
export const API_URL = environment.devURL
export const API_URL1 = "https://www.guestezee.com"
export const DOMAIN_NAME = "https://www.guestezee.com"
export const ENDPOINTS = {
  GETNEWACCESSTOKEN: API_URL + ':5200/refreshtoken',
  VARIABLES: API_URL + ':5413/variables/create',
  VARIABLESUPDATE: API_URL + ':5413/variables/update',
  VARIABLESGETBYID: API_URL + ':9430/variables/getbyid',
  ADD_BRANDS: API_URL + ':5433/brand/create',
  ADD_BRANDSUpdate: API_URL + ':5433/brand/update',
  INVESTOR_UPDATE: API_URL + ':3305/investor/update',
  ADD_POST: API_URL + ':3302/announcement/create',
  IGNORE_POST: API_URL + ':3302/announcement/update',
  INTEREST_POST: API_URL + ':3302/announcement/update',
  ADD_BANNER: API_URL + ':5410/banners/create',
  UPDATE_BANNER: API_URL + ':5410/banners/update',
  GET_BANNER: API_URL + ':9433/banners/getbyid',
  ADD_GIFTMEAL: API_URL + ':5469/giftmeal/create',
  UPDATE_GIFTMEAL: API_URL + ':5469/giftmeal/update',
  GET_GIFTMEAL: API_URL + ':9463/giftmeal/getbyid',
  GET_GIFTMEALSETTINGS: API_URL + ':9544/giftamealsettings/getall',
  GET_TABLESTRUCTURE: API_URL + ':9544/giftamealsettings/getall',
  ADD_TABLEBOOKING: API_URL + ':5463/tablebooking/create',
  UPDATE_TABLEBOOKING: API_URL + ':5463/tablebooking/update',
  GET_TABLEBOOKING: API_URL + ':9453/tablebooking/getbyid',
  GET_CUSTOMEREMAIL: API_URL + ':9473/customermail/getall',
  ADD_CUSTOMER: API_URL + ':5430/customer/create',
  UPDATE_CUSTOMER: API_URL + ':5430/customer/update',
  GET_CUSTOMER: API_URL + ':9416/customer/getbyid',
  GETALLCUSTOMER: API_URL + ':9416/customer/getall',
  ADD_CUSTOMER_ADDRESS: API_URL + ':5431/customeraddress/create',
  UPDATE_CUSTOMER_ADDRESS: API_URL + ':5431/customeraddress/update',
  GET_ALL_CUSTOMER_GROUP: API_URL + ':9415/customergroup/getall',
  GET_CUSTOMER_GROUP: API_URL + ':9415/customergroup/getbyid',
  GET_CUSTOMER_ADDRESS: API_URL + ':9417/customeraddress/getbyid',
  ADD_LOGO_FAV_OPTIONS: API_URL + ':5409/storegallery/create',
  ADD_CUSTOMER_GROUP: API_URL + ':5429/customergroup/create',
  UPDATE_CUSTOMER_GROUP: API_URL + ':5429/customergroup/update',
  ADD_CATEGORY: API_URL + ':5434/category/create',
  UPDATE_CATEGORY: API_URL + ':5434/category/update',
  ADD_STORE_PROFILE: API_URL + ':5407/store/upsert',
  ADD_STORE_SETTINGS: API_URL + ':5408/storesettings/upsert',
  ADD_SHIPPING_SETTINGS: API_URL + ':5423/shippingsettings/create',
  UPDATE_SHIPPING_SETTINGS: API_URL + ':5423/shippingsettings/upsert',
  ADD_INVENTORY_SOURCES: API_URL + ':5428/inventorysources/create',
  ALLBRANDS: API_URL + 'typicode/demo/posts',
  ADD_NOTIFICATION_TOKEN: API_URL + ':7684/notificationtoken/create',
  ADDBRANDGETBYID: API_URL + ':9419/brand/getbyid',
  ADDINVESTORGETBYID: API_URL + ':6530/investor/getbyid',
  POSTGETALL: API_URL + ':6527/announcement/getall',
  NEWSGETALL: API_URL + ':6528/news/getall',
  CLEMEMBERSGETALL: API_URL + ':9422/product/getall',
  STANDARDEMAILTEMPLATEEDIT: API_URL + ':5411/emailtemplate/update',
  STANDARDEMAILTEMPLATEDELETE: API_URL + ':5411/emailtemplate/delete',
  STANDARDEMAILTEMPLATEGETALL: API_URL + ':9428/emailtemplate/getall',
  CUSTOMEMAILTEMPLATE: API_URL + ':5411/emailtemplate/create',
  EMAILTEMPLATEGETBYID: API_URL + ':9428/emailtemplate/getbyid',
  NEWSLETTERTEMPLATE: API_URL + ':5415/newslettertemplate/create',
  NEWSLETTERTEMPLATEUPDATE: API_URL + ':5415/newslettertemplate/update',
  NEWSLETTERTEMPLATEGETBYID: API_URL + ':9431/newslettertemplate/getbyid',
  PRODUCTINFORMATIONCREATE: API_URL + ':5442/staticinfo/create',
  PRODUCTINFORMATIONUPDATE: API_URL + ':5442/staticinfo/update',
  PRODUCTINFORMATIONGETBYID: API_URL + ':9436/staticinfo/getbyid',
  // UpdateStatus : API_URL+':5449/order/updatestatus',
  UpdateStatus: API_URL + ':5449/statusupdate/update',
  GETALLSTATUSVALUES: API_URL + ':9440/orderstatus/getall',
  ORDERDETAILSGETBYID: API_URL + ':9442/order/getbyid',
  ORDERUPDATE: API_URL + ':5473/order/update',
  ORDERCREATE: API_URL + ':5473/order/create',
  REVIEWGETBYID: API_URL + ':9425/productreviews/getall',
  REVIEWUPDATE: API_URL + ':5439/productreviews/update',
  // REVIEWCREATE : API_URL+':5439/productreviews/create',
  // USERSETTINGS_PERMISSIONS: API_URL + ':5404/roles/create',
  USERSETTINGS_PERMISSIONS: API_URL + ':5404/roles/upsert',
  NEWSLETTER_SETTINGS: API_URL + ':5414/newslettersettings/upsert',
  INVENTORY_SETTINGS: API_URL + ':5427/inventorysettings/create',
  CHECKOUT_SETTINGS: API_URL + ':5417/checkoutsettings/create',
  PAYMENT_METHOD: API_URL + ':5419/paymentmethods/create',
  TAX_SETTING: API_URL + ':5422/taxsettings/create',
  SHIPPING_CARRIERS: API_URL + ':5426/customshippingcarriers/create',
  UPDATE_SHIPPING_CARRIERS: API_URL + ':5426/customshippingcarriers/update',
  DELETE_SHIPPING_CARRIERS: API_URL + ':5426/customshippingcarriers/delete',
  GETALL_SHIPPING_CARRIERS: API_URL + ':9412/customshippingcarriers/getall',
  GET_SHIPPING_CARRIERS_BY_ID: API_URL + ':9412/customshippingcarriers/getbyid',
  ADD_USERS: API_URL + ':5403/user/create',
  GET_ALL_COUNTRIES: API_URL + ':5300/es-countries/all',
  ADD_SHIPPING_METHODS: API_URL + ':5425/shippingmethods/create',
  UPDATE_SHIPPING_METHODS: API_URL + ':5425/shippingmethods/update',
  UPSERT_SHIPPING_METHODS: API_URL + ':5425/shippingmethods/upsert',
  GET_ALL_SHIPPING_METHODS: API_URL + ':9411/shippingmethods/getall',
  GET_STATES_BY_ID: API_URL + ':5300/es-states/all',
  GET_ALL_CURRENCIES: API_URL + ':5300/es-currencies/all',
  TAX_CLASS: API_URL + ':5420/taxclass/create',
  UPSERT_TAX_CLASS: API_URL + ':5420/taxclass/upsert',
  UPDATE_TAX_CLASS: API_URL + ':5420/taxclass/update',
  GET_ALL_PRODUCTS: API_URL + ':9422/product/getall',
  GET_ALL_CATEGORY: API_URL + ":9420/category/getall",
  GET_CATEGORY_BYID: API_URL + ":9420/category/getbyid",
  COUPON_CODE_CREATE: API_URL + ":5441/couponcode/create",
  COUPON_CODE_UPDATE: API_URL + ":5441/couponcode/update",
  GET_ALL_SHIPPING_ZONES: API_URL + ":9410/shippingzones/getall",
  ADD_PRODUCT: API_URL + ':5436/product/create',
  UPDATE_PRODUCT: API_URL + ':5436/product/update',
  UPDATE_ANNOUNCEMENT: API_URL + ':3302/announcement/update',
  GET_ALL_BRANDS: API_URL + ":9419/brand/getall",
  ADD_STORE_GALLERY: API_URL + ':5409/storegallery/create',
  UPSERT_STORE_GALLERY: API_URL + ':5409/storegallery/upsert',
  GET_STORE_GALLERY: API_URL + ':9434/storegallery/getall',
  PROMOTIONS_CREATE: API_URL + ":5440/promotions/create",
  PROMOTION_UPDATE: API_URL + ":5440/promotions/update",
  GET_PROMOTIONS_BY_ID: API_URL + ":9426/promotions/getbyid",
  GET_ALL_ROLES: API_URL + ":9401/roles/getall",
  GET_INVENTORY_SOURCE: API_URL + ":9414/inventorysources/getall",
  GET_INVENTORY_SOURCE_BYID: API_URL + ":9414/inventorysources/getbyid",
  UPDATE_INVENTORY_SOURCE: API_URL + ':5428/inventorysources/update',
  DELETE_INVENTORY_SOURCE: API_URL + ':5428/inventorysources/delete',
  DELETE_VARIANT: API_URL + ':5436/product/delete',
  GET_ALL_CURRENCIESS: API_URL + ":9404/currencies/getall",
  // GET_ALL_CURRENCIESS : API_URL + ":5300/es-currencies/all",
  CURRENCY_MANAGEMENT: API_URL + ":5418/currencies/create",
  GET_ALL_TAXCLASS: API_URL + ":9406/taxclass/getall",
  GET_TAXCLASS_BY_ID: API_URL + ":9406/taxclass/getall",
  TAX_ZONES: API_URL + ":5421/taxzone/create",
  UPDATE_TAXZONE: API_URL + ":5421/taxzone/update",
  GET_TAX_ZONE: API_URL + ":9407/taxzone/getall",
  GET_TAX_ZONE_BY_ID: API_URL + ":9407/taxzone/getbyid",
  DELETE_TAX_ZONE: API_URL + ":5421/taxzone/delete",
  GET_ADDED_CURRENCIESS: API_URL + ":9404/currencies/getall",
  // GET_ADDED_CURRENCIESS : API_URL + ":5300/es-currencies/all",
  GET_DEFAULT_CURRENCIESS: API_URL + ":9404/currencies/getall",
  // GET_DEFAULT_CURRENCIESS : API_URL + ":5300/es-currencies/all",
  GET_All_CURRENCIESS: API_URL + ":9404/currencies/getall",
  // GET_All_CURRENCIESS : API_URL + ":5300/es-currencies/all",
  GET_CURRENCY_BY_ID: API_URL + ":9404/currencies/getbyid",
  UPDATE_CURRENCY: API_URL + ":5418/currencies/update",
  DELETE_CURRENCY: API_URL + ":5418/currencies/delete",
  DELETE_ANNOUNCEMENT: API_URL + ":3302/announcement/delete",
  GET_PRODUCT_BYID: API_URL + ":9422/product/getbyid",

  SEND_IMAGE: API_URL + ":9432/imageupload/create",
  DELETE_IMAGE: API_URL + ":9432/imageupload/delete",
  LOGIN: API_URL + ":5200/login",

  GET_ALL_USERS: API_URL + ":9400/user/getall",
  GET_USERS_BY_ID: API_URL + ":9400/user/getbyid",
  UPDATE_USER: API_URL + ":5403/user/update",
  UPDATE_PASSWORD: API_URL + ":5403/user/update",
  UPDATE_PASSWORD1: API_URL + ":5447/customer/ams-forgot-password",
  DELETE_USER: API_URL + ":5403/user/delete",
  CHECK_EXISTINGUSER: API_URL + ":9978/ams/check-user",
  GENERATE_TEMPORARY_PASSWORD: API_URL + ":9996/communication/GenerateTemporaryPassword",
  VERIFY_TEMPORARY_PASSWORD: API_URL + ":9996/communication/VerifyTemporaryPassword",

  GET_ALL_PAYMENTS: API_URL + ":9405/paymentmethods/getall",
  UPSERT_PAYMENT: API_URL + ":5419/paymentmethods/upsert",

  GET_SHIPPING_SETTING_ALL: API_URL + ":9409/shippingsettings/getall",
  GET_STORE_SETTING_ALL: API_URL + ":9402/storesetting/getall",
  GET_STORE_ALL: API_URL + ":9435/store/getall",
  INVENTORY_GETALL: API_URL + ":9413/inventorysettings/getall",
  INVENTORY_UPSERT: API_URL + ":5427/inventorysettings/upsert",
  CHECKOUTSETTINGS_GET_ALL: API_URL + ":9403/checkoutsettings/getall",
  CHECKOUTSETTINGS_UPSERT: API_URL + ":5417/checkoutsettings/upsert",
  // LOGIN : API_URL + ":5200/login"

  GET_ALL_TAX_SETTING: API_URL + ":9408/taxsettings/getall",
  UPSERT_TAX_SETTING: API_URL + ":5422/taxsettings/upsert",

  CREATE_VARIANT: API_URL + ":5437/variants/create",
  UPDATE_VARIANT: API_URL + ":5437/variants/update",
  GET_VARIANT_BY_ID: API_URL + ":9423/variants/getbyid",

  GET_NEWSLETTER_SETTINGS: API_URL + ":9429/newslettersettings/getall",
  GET_ROLES: API_URL + ":9401/roles/getall",

  CREATE_PRODUCT_FILTER_GROUP: API_URL + ":5435/filtergroup/create",
  UPDATE_PRODUCT_FILTER_GROUP: API_URL + ":5435/filtergroup/update",
  DELETE_PRODUCT_FILTER_GROUP: API_URL + ":5435/filtergroup/delete",
  GET_PRODUCT_FILTER_GROUP: API_URL + ":9421/filtergroup/getall",
  GET_PRODUCT_FILTER_GROUP_BYID: API_URL + ":9421/filtergroup/getbyid",

  GET_ALL_ORDER_STATUS: API_URL + ":9440/orderstatus/getall",
  GET_ALL_SHIPMENT: API_URL + ":9441/shippment/getall",
  GET_SHIPMENT_BY_ID: API_URL + ":9441/shippment/getbyid",

  CREATE_SHIPMENT: API_URL + ":5448/shippment/create",
  UPDATE_SHIPMENT: API_URL + ":5448/shippment/update",
  GET_ORDER_BY_ID: API_URL + ":9442/order/getbyid",

  CREATE_ORDER_ACTIVITY: API_URL + ":5462/orderhistory/create",
  GET_ORDER_HISTORY: API_URL + ":9451/orderhistory/getall",

  CREATE_TABLEBOOKING_ACTIVITY: API_URL + ":5471/tablebookinghistory/create",
  GET_TABLEBOOKING_HISTORY: API_URL + ":9465/tablebookinghistory/getall",
  GET_TABLEBOOKING_HISTORY_ID: API_URL + ":9465/tablebookinghistory/getbyid",
  TABLEBOOKING_UPDATESTATUS: API_URL + ':5476/tablebooking/update',

  CREATE_GIFTMEAL_ACTIVITY: API_URL + ":5474/giftmealhistory/create",
  GET_GIFTMEAL_HISTORY: API_URL + ":9476/giftmealhistory/getall",
  GET_GIFTMEAL_HISTORY_ID: API_URL + ":9476/giftmealhistory/getbyid",
  GIFTMEAL_UPDATESTATUS: API_URL + ': 5475/giftmeal/update',

  GET_ALL_INTERNAL_NOTES: API_URL + ":9452/orderinternalnotes/getall",
  CREATE_INTERNAL_NOTE: API_URL + ":5461/orderinternalnotes/create",
  DELETE_INTERNAL_NOTE: API_URL + ":5461/orderinternalnotes/delete",

  SEARCH_CATEGORY: API_URL + ":9471/autocomplete/category",
  SEARCH_PRODUCT: API_URL + ":9471/autocomplete/product",

  SEARCH_LOYALTY_PRPGRAM_MEMBER: API_URL + ":9489/loyalityprogrammember/getbyname",
  OUTLET_CREATE: API_URL + ":5464/outlet/create",
  OUTLET_UPDATE: API_URL + ":5464/outlet/update",
  OUTLET_DELETE: API_URL + ":5464/outlet/delete",
  OUTLET_GETALL: API_URL + ":9454/outlet/getall",
  OUTLET_GETBYID: API_URL + ":9454/outlet/getbyid",
  GET_ORDERDELIVERIES_BY_ID: API_URL + ":9464/orderdeliverylogs/getbyid",

  GET_ALL_CARTS: API_URL + ":9461/cart/getall",
  GET_CART_BY_ID: API_URL + ":9461/cart/getbyid",

  CREATE_APIINTEGRATION_SETTINGS: API_URL + ':5472/ecomintegrationsettings/create',
  EDIT_APIINTEGRATION_SETTINGS: API_URL + ':5472/ecomintegrationsettings/update',
  DELETE_APIINTEGRATION_SETTINGS: API_URL + ':5472/ecomintegrationsettings/delete',
  APIINTEGRATION_BY_ID: API_URL + ':9466/ecomintegrationsettings/getbyid',
  GET_ALL_ORDER_DELIVERY_LOGS: API_URL + ":9464/orderdeliverylogs/getall",
  GET_ALL_API_INT_SETTINGS: API_URL + ":9466/ecomintegrationsettings/getall",
  GET_ALL_ORDER_DETAILS: API_URL + ":9442/order/getall",
  NEWSLETTER_QUEUE_CREATE: API_URL + ":5416/newsletterqueue/create",
  NEWSLETTER_QUEUE_UPDATE: API_URL + ":5416/newsletterqueue/update",
  NEWSLETTER_QUEUE_DELETE: API_URL + ":5416/newsletterqueue/delete",
  NEWSLETTER_TEMPLATE_GET_BY_ID: API_URL + ":9431/newslettertemplate/getbyid",
  NEWSLETTER_TEMPLATE_GET_ALL: API_URL + ":9431/newslettertemplate/getall",
  NEWSLETTER_QUEUE_GET_ALL: API_URL + ":9462/newsletterqueue/getall",
  NEWSLETTER_QUEUE_GET_BY_ID: API_URL + ":9462/newsletterqueue/getbyid",
  GET_TABLE_BOOKING_HISTORY: API_URL + ":9465/tablebookinghistory/getall",
  GETALL_TAXCLASSES: API_URL + ":9484/taxclass/getall",
  GETTAXCLASSES: API_URL + ":9485/taxzonefororder/getall",

  GET_SHIPPING_METHODS: API_URL + ":9535/shippingmethods/getall",

  GET_SEARCH_ORDERS: API_URL + ":9474/searchorder/getall",
  GET_ORDER_CSV: API_URL + ":6523/report/DownloadOrdersCSV",


  ADD_PRIVACY_POLICY: API_URL + ":5477/privacypolicy/create",
  ADD_TERMS_CONDITIONS: API_URL + ":5478/termsandconditions/create",
  ADD_NEWS: API_URL + ":3303/news/create",
  UPDATE_PRIVACY_POLICY: API_URL + ":5477/privacypolicy/update",
  UPDATE_TERMS_CONDITIONS: API_URL + ":5478/termsandconditions/update",
  GETALL_PRIVACY_POLICY: API_URL + ":9477/privacypolicy/getall",
  GETALL_TERMS_CONDITIONS: API_URL + ":9478/termsandconditions/getall",

  ADD_RECURRING_PROFILES: API_URL + ":5482/recurringprofiles/create",
  UPDATE_RECURRING_PROFILES: API_URL + ":5482/recurringprofiles/update",
  GET_ALL_RECURRING_PROFILES: API_URL + ":9486/recurringprofiles/getall",
  GET_RECURRING_PROFILES: API_URL + ":9486/recurringprofiles/getbyid",
  DELETE_RECURRING_PROFILES: API_URL + ":5482/recurringprofiles/delete",
  ADD_VOUCHER_DEFINITION: API_URL + ":5487/voucherdefinition/create",
  UPDATE_VOUCHER_DEFINITION: API_URL + ":5487/voucherdefinition/update",
  GETBYID_VOUCHER_DEFINITION: API_URL + ":9495/voucherdefinition/getbyid",
  ADD_LOYALTY_PROGRAM_MEMBER: API_URL + ":5485/loyalityprogrammember/create",
  UPDATE_LOYALTY_PROGRAM_MEMBER: API_URL + ":5485/loyalityprogrammember/update",
  GETBYID_LOYALTY_PROGRAM_MEMBER: API_URL + ":9489/loyalityprogrammember/getbyid",
  ADD_LOYALTY_PROGRAM_PARTNER: API_URL + ":5486/loyalityprogrampartner/create",
  UPDATE_LOYALTY_PROGRAM_PARTNER: API_URL + ":5486/loyalityprogrampartner/update",
  GETBYID_LOYALTY_PROGRAM_PARTNER: API_URL + ":9490/loyalityprogrampartner/getbyid",

  LOYALTY_CREATE: API_URL + ":5483/loyaltytier/create",
  LOYALTY_UPDATE: API_URL + ":5483/loyaltytier/update",
  LOYALTY_DELETE: API_URL + ":5483/loyaltytier/delete",
  LOYALTY_PROG_CURRENCY_CREATE: API_URL + ":5484/loyalityprogramcurrency/create",
  LOYALTY_PROG_CURRENCY_UPDATE: API_URL + ":5484/loyalityprogramcurrency/update",
  LOYALTY_PROG_CURRENCY_DELETE: API_URL + ":5484/loyalityprogramcurrency/delete",
  LOYALTY_TIER_GET_ALL: API_URL + ":9487/loyalitytier/getall",
  LOYALTY_TIER_GET_BY_ID: API_URL + ":9487/loyalitytier/getbyid",
  LOYALTY_PROG_CURRENCY_GET_ALL: API_URL + ':9488/loyalityprogramcurrency/getall',
  LOYALTY_PROG_CURRENCY_GET_BY_ID: API_URL + ':9488/loyalityprogramcurrency/getbyid',
  LOYALTY_TIER_BENFIT_GETALL: API_URL + ':9498/loyaltytierbenefit/getall',
  LOYALTY_PROGRAM_GET_ALL: API_URL + ':9491/loyalityprogram/getall',
  LOYALTY_TIER_GROUP_GET_ALL: API_URL + ':9492/loyalitytiergroup/getall',

  LOYALTY_PROGRAM_MEMBER_GETBYID: API_URL + ':9489/loyalityprogrammember/getbyid',
  LOYALTY_PROGRAM_MEMBER_GETALL: API_URL + ':9489/loyalityprogrammember/getall',
  LOYALTY_PROGRAM_MEMBER_CREATE: API_URL + ':5485/loyalityprogrammember/create',
  LOYALTY_PROGRAM_MEMBER_UPDATE: API_URL + ':5485/loyalityprogrammember/update',

  CREATE_LOYALTY_PROGRAM: API_URL + ":5488/loyalityprogram/create",
  UPDATE_LOYALTY_PROGRAM: API_URL + ":5488/loyalityprogram/update",
  DELETE_LOYALTY_PROGRAM: API_URL + ":5488/loyalityprogram/delete",
  GETALL_LOYALTY_PROGRAM: API_URL + ":9491/loyalityprogram/getall",
  GET_BY_ID_LOYALTY_PROGRAM: API_URL + ":9491/loyalityprogram/getbyid",

  CREATE_LOYALTY_TIER_GROUP: API_URL + ":5489/loyalitytiergroup/create",
  UPDATE_LOYALTY_TIER_GROUP: API_URL + ":5489/loyalitytiergroup/update",
  DELETE_LOYALTY_TIER_GROUP: API_URL + ":5489/loyalitytiergroup/delete",
  GETALL_LOYALTY_TIER_GROUP: API_URL + ":9492/loyalitytiergroup/getall",
  GET_BY_ID_LOYALTY_TIER_GROUP: API_URL + ":9492/loyalitytiergroup/getbyid",

  LOYALTY_PROMOTION_GET_ALL: API_URL + ':9502/loyaltypromotion/getall',
  LOYALTY_PROMOTION_GET_BY_ID: API_URL + ':9502/loyaltypromotion/getbyid',
  LOYALTY_PROMOTION_CREATE: API_URL + ':5499/loyaltypromotion/create',
  LOYALTY_PROMOTION_UPDATE: API_URL + ':5499/loyaltypromotion/update',
  LOYALTY_PROMOTION_DELETE: API_URL + ':5499/loyaltypromotion/delete',

  BENEFIT_TYPE_CREATE: API_URL + ":5507/benefittype/create",
  BENEFIT_TYPE_UPDATE: API_URL + ":5507/benefittype/update",
  BENEFIT_TYPE_DELETE: API_URL + ":5507/benefittype/delete",
  BENEFIT_TYPE_GET_ALL: API_URL + ":9510/benefittype/getall",
  BENEFIT_TYPE_GET_BY_ID: API_URL + ":9510/benefittype/getbyid",
  BENEFIT_CREATE: API_URL + ':5494/benefit/create',
  BENEFIT_UPDATE: API_URL + ':5494/benefit/update',
  BENEFIT_GETBYID: API_URL + ':9497/benefit/getbyid',
  BENEFIT_TYPE_GETALL: API_URL + ':9510/benefittype/getall',

  LOYALTY_PARTNER_GET_ALL: API_URL + ':9494/loyaltypartner/getall',
  LOYALTY_PARTNER_GET_BY_ID: API_URL + ':9494/loyaltypartner/getbyid',
  LOYALTY_PARTNER_CREATE: API_URL + ':5491/loyaltypartner/create',
  LOYALTY_PARTNER_UPDATE: API_URL + ':5491/loyaltypartner/update',
  LOYALTY_PARTNER_DELETE: API_URL + ':5491/loyaltypartner/delete',

  LOYALTY_PARTNER_CONTACT_GET_ALL: API_URL + ':9496/loyalitypartnercontact/getall',
  LOYALTY_PARTNER_CONTACT_GET_BY_ID: API_URL + ':9496/loyalitypartnercontact/getbyid',
  LOYALTY_PARTNER_CONTACT_CREATE: API_URL + ':5493/loyaltypartnercontact/create',
  LOYALTY_PARTNER_CONTACT_UPDATE: API_URL + ':5493/loyalitypartnercontact/update',
  LOYALTY_PARTNER_CONTACT_DELETE: API_URL + ':5493/loyalitypartnercontact/delete',

  MARKET_SEG_CREATE: API_URL + ':5502/marketsegment/create',
  MARKET_SEG_UPDATE: API_URL + ':5502/marketsegment/update',
  MARKET_SEG_DELETE: API_URL + ':5502/marketsegment/delete',
  MARKET_SEG_GET_ALL: API_URL + ':9505/marketsegment/getall',
  MARKET_SEG_GET_BY_ID: API_URL + ':9505/marketsegment/getbyid',

  LOYALTY_PROGRAM_MEMBER_FETCH_BY_LOYALTY_ID: API_URL + ":9489/loyalityprogrammember/getbyprogramid",

  PROMOTION_MARKET_CREATE: API_URL + ":5501/promotionmarketsegment/create",
  PROMOTION_MARKET_UPDATE: API_URL + ":5501/promotionmarketsegment/update",

  GET_ALL_MERCHANTS: API_URL + ":9525/merchant/getall",
  GET_BY_ID_MERCHANTS: API_URL + ":9525/merchant/getbyid",

  GET_ALL_ORDER_FLOW_STATUS: API_URL + ":9529/orderstatusflow/getall",

  CREATE_ACCEPTANCE_TIMING: API_URL + ":5515/acceptancetimings/upsert",
  GETALL_ACCEPTANCE_TIMING: API_URL + ":9532/acceptancetimings/getall",
  GET_PROMOTION_BYDATE: API_URL + ":9538/promotions/getall",
  GET_ALL_SHIPPING_CARRIERS: API_URL + ":9537/customshippingcarriers/getall",
  GET_RATES: API_URL + ":9467/orderdelivery/getrates",
  DUNZO_CHARGES: API_URL + ':9577/orderdelivery/quote',
  DUNZO: API_URL + ':9595/orderdelivery/quote',
  PICKDROP: API_URL + ':9596/orderdelivery/getrates',
  DELHIVERY: API_URL + ':9597/orderdelivery/invoiceCharge',
  PAYMENT_METHODS: API_URL + ":9541/paymentmethods/getall",
  GETALL_ORDER_STATUS: API_URL + ':9440/orderstatus/getall',
  TAXSETTINGS: API_URL + ':9408/taxsettings/getall',
  GET_TAXZONES: API_URL + ':9407/taxzone/getall',
  ORDER_STATUS_FLOW: API_URL + ':9529/orderstatusflow/getall',
  PICKANDDROP: API_URL + ':9467/orderdelivery/getrates',
  GET_CURRENCIES: API_URL + ':9404/currencies/getall',
  GETALL_GIFTMEALSETTINGS: API_URL + ':9543/giftamealsettings/getall',
  CREATE_GIFTMEALSETTINGS: API_URL + ':5517/giftamealsettings/create',
  UPDATE_GIFTMEALSETTINGS: API_URL + ':5517/giftamealsettings/update',
  GETALL_TABLESTRUCTURE: API_URL + ':9543/giftamealsettings/getall',
  CREATE_TABLESTRUCTURE: API_URL + ':5517/giftamealsettings/create',
  UPDATE_TABLESTRUCTURE: API_URL + ':5517/giftamealsettings/update',
  CREATE_CUSTOMER_CONTACT: API_URL + ':5519/customercontact/create',
  UPDATE_CUSTOMER_CONTACT: API_URL + ':5519/customercontact/update',
  GETBYID_CUSTOMER_CONTACT: API_URL + ':9546/customercontact/getbyid',
  feedBackGetAll: API_URL + ':9547/feedbackform/getall',
  // CREATE_TABLEBOOKINGSETTINGS: API_URL + ':7787/tablebookingsettings/create',
  CREATE_TABLEBOOKINGSETTINGS: API_URL + ':7787/tablebookingsettings/upsert',
  UPDATE_TABLEBOOKINGSETTINGS: API_URL + ':7787/tablebookingsettings/update',
  GETALL_TABLEBOOKINGSETTINGS: API_URL + ':9200/tablebokkingsettings/getall',
  ORDERSTATUSGETBYID: API_URL + ':9440/orderstatus/getbyid',
  ORDERSTATUSUPDATE: API_URL + ':5465/orderstatus/update',
  GET_ORGANIZATION: API_URL + ':9557/organization/getall',
  CREATE_ROLE: API_URL + ':5572/roles/create',
  UPDATE_ROLE: API_URL + ':5572/roles/update',
  DELETE_ROLE: API_URL + ':5404/roles/delete',
  GET_ROLE_BY_ID: API_URL + ':9602/roles/getbyid',
  GETAll_ROLES: API_URL + '9602/roles/getall',

  STORE_PERMISSION_CREATE: API_URL + ":5573/store-permission/create",
  STORE_PERMISSION_UPDATE: API_URL + ":5573/store-permission/update",
  STORE_PERMISSION_DELETE: API_URL + ":5573/store-permission/delete",

  STORE_PERMISSION_GETBYID: API_URL + ":9624/store-permission/getbyid",
  STORE_PERMISSION_GETALL: API_URL + ":9624/store-permission/getall",

  OUTLET_PERMISSION_CREATE: API_URL + ":5570/outlet-permission/create",
  OUTLET_PERMISSION_UPDATE: API_URL + ":5570/outlet-permission/update",
  OUTLET_PERMISSION_DELETE: API_URL + ":5570/outlet-permission/delete",

  OUTLET_PERMISSION_GETBYID: API_URL + ":9625/outlet-permission/getbyid",
  OUTLET_PERMISSION_GETALL: API_URL + ":9625/outlet-permission/getall",

  AUTH_PROFILE_CREATE: API_URL + ":5571/profile/create",
  AUTH_PROFILE_UPDATE: API_URL + ":5571/profile/update",
  AUTH_PROFILE_DELETE: API_URL + ":5571/profile/delete",

  AUTH_PROFILE_GETBYID: API_URL + ":9601/profile/getbyid",
  AUTH_PROFILE_GETALL: API_URL + ":9601/profile/getall",

  CREATE_ISSUE_VOUCHER: API_URL + ":5498/voucher/create",
  UPDATE_ISSUE_VOUCHER: API_URL + ":5498/voucher/update",
  DELETE_ISSUE_VOUCHER: API_URL + ":5498/voucher/delete",

  GETALL_ISSUE_VOUCHER: API_URL + ":9501/voucher/getall",
  GET_ISSUE_VOUCHER: API_URL + ":9501/voucher/getbyid",

  TRANSACTION_JOURNAL_CREATE: API_URL + ":5503/transactionjournal/create",
  TRANSACTION_JOURNAL_UPDATE: API_URL + ":5503/transactionjournal/update",
  TRANSACTION_JOURNAL_DELETE: API_URL + ":5503/transactionjournal/delete",

  TRANSACTION_JOURNAL_GETALL: API_URL + ":9506/transactionjournal/getall",
  TRANSACTION_JOURNAL_GETBYID: API_URL + ":9506/transactionjournal/getbyid",

  GET_ALL_PROMOTION: API_URL + ":9426/promotions/getall",
  GET_ALL_PROMOTION_PRODUCTS: API_URL + ":9426/promotions/getproducts",

  CANCELLATION_POLICY: API_URL + ":5600/cancellation/create",
  RETURN_POLICY: API_URL + ":5601/returnandexchange/create",
  GET_CANCELLATIONPOLICY: API_URL + ":9600/cancellation/getall",
  GET_RETURNPOLICY: API_URL + ":9601/returnandexchange/getall",
  UPDATE_CANCELLATION: API_URL + ":5600/cancellation/update",
  UPDATE_EXCHANGE: API_URL + ":5601/returnandexchange/update",

  ADD_SHIPPING_DELIVERY: API_URL + ":5602/shippinganddelivery/create",
  UPDATE_SHIPPING_DELIVERY: API_URL + ":5602/shippinganddelivery/update",
  GETALL_SHIPPING_DELIVERY: API_URL + ":9604/shippinganddelivery/getall",

  CREATE_ROLES: API_URL + ":5404/roles/create",
  UPDATE_ROLES: API_URL + ":5404/roles/update",
  GETBYID_ROLES: API_URL + ":9401/roles/getbyid",
  CREATE_ADMINUSERS: API_URL + ":5403/user/create",
  UPDATE_ADMINUSERS: API_URL + ":5403/user/update",
  GETBYID_ADMINUSERS: API_URL + ":9400/user/getbyid",
  GETALL_ADMINUSERS: API_URL + ":9401/roles/getall",

  ABOUT_US_CREATE: API_URL + ":5481/aboutus/create",
  ABOUT_US_UPDATE: API_URL + ":5481/aboutus/update",
  GETALL_ABOUT_US: API_URL + ":9608/aboutus/getall",

  FAQ_CREATE: API_URL + ":5480/FAQ/create",
  FAQ_UPDATE: API_URL + ":5480/FAQ/update",
  GETALL_FAQ: API_URL + ":9912/FAQ/getall",

  BLOG_CREATE: API_URL + ":5479/blog/create",
  BLOG_UPDATE: API_URL + ":5479/blog/update",
  GETALL_BLOG: API_URL + ":9913/blog/getall",

  CONTACT_US_CREATE: API_URL + ":5605/contactus/create",
  CONTACT_US_UPDATE: API_URL + ":5605/contactus/update",
  GETALL_CONTACT_US: API_URL + ":9609/contactus/getall",

  GETALL_WISHLIST: API_URL + ":9613/wishlist/getall",
  GETBYID_WISHLIST: API_URL + ":9613/wishlist/getbyid",

  GET_CHECKOUT_FLOW: API_URL + ":9611/checkoutprocessflow/getall",
  ADD_MEMBER: API_URL + ':7401/member/create',
  UPDATE_MEMBER: API_URL + ':7401/member/update',
  GET_MEMBERBYID: API_URL + ':8903/member/getbyid',
  ADD_ENQUIRY: API_URL + ':7402/enquiry/create',
  UPDATE_ENQUIRY: API_URL + ':7402/enquiry/update',
  GET_ENQUIRYBYID: API_URL + ':8904/enquiry/getbyid',
  GET_FILTER_PRODUCTS: API_URL + ':9448/product/filterproducts',
  GET_CUSTOMER_BY_NAME: API_URL + ':9100/search/customer',
  CREATE_EVENT: API_URL + ':6999/event/create',
  CREATE_EVENT_ELIGIBILITY: API_URL + ':6992/eligibility/create',
  UPDATE_EVENT_ELIGIBILITY: API_URL + ':6992/eligibility/update',
  UPDATE_EVENT: API_URL + ':6999/event/update',
  DELETE_EVENT: API_URL + ':6898/event/delete',
  GETALL_EVENT: API_URL + ':6555/event/getall',
  GET_EVENTBYID: API_URL + ':6555/event/getbyid',
  GET_EVENTELIGIBILITYBYID: API_URL + ':6993/eligibility/getbyid',
  GET_FORMBYID: API_URL + ':6899/forms/getbyid',
  UPDATE_FORM: API_URL + ':7499/forms/update',
  GET_ALL_EVENTELIGIBILITY: API_URL + ':6993/eligibility/getall',
  FORMS_GETALL: API_URL + ':6899/forms/getall',
  ORDER_UPDATION: API_URL + ':5456/order/upsert',
  HDFC_PAYMENT: API_URL + ":5621/api/payment/generateHDFCLink",
  GETBYID_ORDERS: API_URL + ':9475/order/getbyid',
  DELETE_CUSTOMER: API_URL + ":5430/customer/delete",




  //newly added services
  CREATE_SERVICE: API_URL1 + ':7780/services/create',
  UPDATE_SERVICE: API_URL1 + ':7780/services/update',
  DELETE_SERVICE: API_URL1 + ':7780/services/delete',
  GETALL_SERVICE: API_URL1 + ':9979/services/getall',
  GETBYID_SERVICE: API_URL1 + ':9979/services/getbyid',

  CREATE_HIERARCHY: API_URL1 + ':3391/hierarchy/create',
  UPDATE_HIERARCHY: API_URL1 + ':3391/hierarchy/update',
  DELETE_HIERARCHY: API_URL1 + ':3391/hierarchy/delete',
  GETALL_HIERARCHY: API_URL1 + ':3390/hierarchy/getall',
  GETBYID_HIERARCHY: API_URL1 + ':3390/hierarchy/getbyid',



  ADD_RENEWAL: API_URL1 + ':3391/hierarchy/create',
  UPDATE_RENEWAL: API_URL1 + ':3391/hierarchy/update',
  DELETE_RENEWAL: API_URL1 + ':3391/hierarchy/delete',
  GETALL_RENEWAL: API_URL1 + ':3390/hierarchy/getall',
  GETBYID_RENEWAL: API_URL1 + ':3390/hierarchy/getbyid',


  GET_LOGIN_CUSTOMER: API_URL1 + ':9526/customer/getbyid',
  GET_PROPERTY_SIZE: API_URL + ':1216/propertysize/getall',


  CREATE_PAYMENT_SUBSCRIPTION: API_URL + ':8839/paymentsubscription/create',
  UPDATE_PAYMENT_SUBSCRIPTION: API_URL + ':8839/paymentsubscription/update',
  GETALL_PAYMENT_SUBSCRIPTION: API_URL + ':8840/paymentsubscription/getall',
  EMAIL_APPROVAL_: API_URL + ':5622/sms/GenerateSMS',

  //for service tab in hotels
  GET_ALL_TABS: API_URL1 + ":1297/servicetabdetails/getall",
  GET_TAB_BY_ID: API_URL1 + ":1297/servicetabdetails/getall",



}